version: '3'

services:
    notebooks:
        build:
          context: .
          dockerfile: Dockerfile
        volumes:
          - ./notebooks:/opt/notebooks
        ports:
          - "8888:8888"
        command: bash -c  "./opt/conda/bin/jupyter notebook --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"


     
